services:
  api:
    build: .
    container_name: backend
    ports:
      - "5165:5165"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # 👇 Conexión a tu base local (no al contenedor)
      - ConnectionStrings__DefaultConnection=Host=localhost;Port=5432;Database=AgoraSoft;Username=postgres;Password=admin
    networks:
      - backend-net

networks:
  backend-net:
